# Generated by Django 5.1.2 on 2024-11-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='post/1.png', upload_to='post'),
        ),
    ]
