# Generated by Django 5.1.2 on 2024-10-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=60)),
                ('country', models.CharField(default='morocco', max_length=10)),
            ],
        ),
    ]
