# Generated by Django 5.1.2 on 2024-10-30 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wife',
            name='husband',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='relationships.husband'),
        ),
    ]
