# Generated by Django 5.1.2 on 2024-10-30 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0003_alter_wife_husband'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wife',
            name='husband',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='relationships.husband'),
        ),
    ]
